- configs/DevNet/approved-sv-id-values.yaml
https://lists.sync.global/g/supervalidator-announce/message/26
> Change weight from Tradeweb-Markets to Tradeweb-Markets-1

- configs/DevNet/approved-sv-id-values.yaml
- configs/MainNet/approved-sv-id-values.yaml
- configs/TestNet/approved-sv-id-values.yaml
https://lists.sync.global/g/supervalidator-announce/topic/vote_proposal_to_add_copper/111029918
> chore: CIP-0039 increase GSF weight to 28

- configs/DevNet/approved-sv-id-values.yaml
- configs/MainNet/approved-sv-id-values.yaml
- configs/TestNet/approved-sv-id-values.yaml
Updated PR with the right weights and to all networks now
https://lists.sync.global/g/supervalidator-announce/topic/vote_proposal_to_add_elliptic/111270793
> chore: CIP-0044 add Elliptic weight to the GSF SV

- configs/DevNet/approved-sv-id-values.yaml
- configs/MainNet/approved-sv-id-values.yaml
- configs/TestNet/approved-sv-id-values.yaml
Updated link to the corresponding topic: https://lists.sync.global/g/supervalidator-announce/topic/vote_proposal_to_add_circle/111408806
> chore: CIP-0041 add Circle weight to the GSF SV

- .github/workflows/pull_request.yml
- scripts/check-sum-reward-weights-change.sh
This eases local debugging and simplifies the workflow
> actions: Move sum reward weights check to a script

- configs/DevNet/approved-sv-id-values.yaml
- configs/MainNet/approved-sv-id-values.yaml
- configs/TestNet/approved-sv-id-values.yaml
https://lists.sync.global/g/supervalidator-announce/topic/vote_proposal_to_add_obsidian/111941282
> Add Obsidian Systems weight to GSF SV [allow-total-reward-weight-change]

- configs/DevNet/approved-sv-id-values.yaml
- configs/MainNet/approved-sv-id-values.yaml
- configs/TestNet/approved-sv-id-values.yaml
Added pubkeys of dedicated LCV SV for devnet, testnet.
> Add dedicated LCV SV

- configs/DevNet/approved-sv-id-values.yaml
- configs/MainNet/approved-sv-id-values.yaml
- configs/TestNet/approved-sv-id-values.yaml
https://lists.sync.global/g/supervalidator-announce/topic/vote_proposal_to_add_circle/112158604
> CIP-0041 Add Circle weight to the GSF SV

- configs/MainNet/approved-sv-id-values.yaml
CIP-0034: https://github.com/global-synchronizer-foundation/cips/blob/main/cip-0032-0033-0034-0036-0038-0039-0040/cip-0032-0033-0034-0036-0038-0039-0040.pdf
Mailing list: https://lists.sync.global/g/cip-announce/message/1
> Add Proof-Group-1 to MainNet

- configs/MainNet/approved-sv-id-values.yaml
CIP
https://github.com/global-synchronizer-foundation/cips/blob/main/cip-0035/cip-0035.pdf
Annoucement
https://lists.sync.global/g/cip-announce/message/7
> add Five North mainnet sv key

- configs/DevNet/approved-sv-id-values.yaml
- configs/MainNet/approved-sv-id-values.yaml
- configs/TestNet/approved-sv-id-values.yaml
https://lists.sync.global/g/supervalidator-announce/topic/vote_proposal_to_transfer/112319366
> Transfer weight from GSF to Five-North-1

- .github/workflows/daily_checks.yml
- .github/workflows/pull_request.yml
> actions: Add summaries

- scripts/check-sum-reward-weights-change.sh
This message needs to be in GitHub Actions check summary
> check-sum-reward-weights-change.sh: Send error message to stdout

- configs/DevNet/approved-sv-id-values.yaml
Links:
- https://lists.sync.global/g/tokenomics-announce/message/82
> devnet: Increase weight for SV-Nodeops

- configs/TestNet/approved-sv-id-values.yaml
Links:
- https://lists.sync.global/g/tokenomics-announce/message/82
> testnet: Increase weight for SV-Nodeops

- configs/MainNet/approved-sv-id-values.yaml
Links:
- https://lists.sync.global/g/tokenomics-announce/message/82
> mainnet: Increase weight for SV-Nodeops

- scripts/get-missing-voters.sh
Examples:
```
$ scripts/get-missing-voters.sh 1  # Expiring in 1 day
There are vote requests requiring attention, votes are needed from:
- MainNet: Proof-Group-1
```
```
$ scripts/get-missing-voters.sh 5  # Expiring in 5 days
There are vote requests requiring attention, votes are needed from:
- MainNet: Cumberland-1, Cumberland-2, Digital-Asset-2, Proof-Group-1
```
> scripts: Add get-missing-voters.sh

- scripts/diff-reward-weights.sh
Ignore extra SVs from YAML files
Before (note `Bitwave-1`)
```diff
DevNet/approved-sv-id-values.yaml -> https://docs.dev.global.canton.network.sync.global/dso
--- DevNet/approved-sv-id-values.yaml
+++ https://docs.dev.global.canton.network.sync.global/dso (last modified 24 seconds ago)
@@ -1,8 +1,7 @@
{
-  "Bitwave-1": 0,
"C7-Technology-Services-Limited": 105750,
-  "Cumberland-1": 130000,
-  "Cumberland-2": 130000,
+  "Cumberland-1": 136125,
+  "Cumberland-2": 136125,
"DA-Helm-Test-Node": 10000,
"Digital-Asset-1": 159250,
"Digital-Asset-2": 159250,
TestNet/approved-sv-id-values.yaml -> https://docs.test.global.canton.network.sync.global/dso
Files TestNet/approved-sv-id-values.yaml and https://docs.test.global.canton.network.sync.global/dso (last modified 238 seconds ago) are identical …
```
> diff-reward-weights.sh: Skip missing SVs

- configs/DevNet/approved-sv-id-values.yaml
Redoing https://github.com/global-synchronizer-foundation/configs/pull/85
> /chore [allow-total-reward-weight-change]

- .github/workflows/daily_checks.yml
This reverts commit eaee690fabcffe9eda9be5a4ec52f9f2cd74cb35.
> Revert "Temporarily disabling Slack notifications for weight diffs"

- .github/workflows/pull_request.yml
Fixes an issue where a pull request added to a queue waits indefinitely for the checks to complete.
> actions: Trigger checks for merge queues

- configs/DevNet/approved-sv-id-values.yaml
- configs/MainNet/approved-sv-id-values.yaml
- configs/TestNet/approved-sv-id-values.yaml
https://lists.sync.global/g/tokenomics-announce/message/82
> Update ProofGroup SV weight

- configs/DevNet/approved-sv-id-values.yaml
> DevNet: Correct new SV ID key for Digital-Asset-1
